import { readFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import assert from 'node:assert/strict';
const fields = new Map(Object.entries({name:'Alex & Sam',email:'client@example.com',eventType:'Wedding',eventDate:'2027-02-14',message:'Please share availability & rates.\nVenue: Tagaytay.'}));
const elements = new Map();
let handler;
const document = {getElementById(id){if(!elements.has(id)) elements.set(id,{textContent:'',firstChild:{textContent:''},hidden:true,addEventListener(_,fn){handler=fn;}});return elements.get(id);}};
const window={location:{href:''}};
const context={window,document,Date,FormData:class{get(key){return fields.get(key);}},navigator:{clipboard:{async writeText(){throw Error('Not expected with email configured');}}}};
runInNewContext(readFileSync(new URL('./dist/config.js',import.meta.url),'utf8'),context);
runInNewContext(readFileSync(new URL('./dist/script.js',import.meta.url),'utf8'),context);
await handler({preventDefault(){}});
const mail=new URL(window.location.href);
assert.equal(mail.protocol,'mailto:');
assert.equal(decodeURIComponent(mail.pathname),'mlagellon@gmail.com');
assert.equal(mail.searchParams.get('subject'),'Wedding inquiry — Alex & Sam');
assert(mail.searchParams.get('body').includes('availability & rates.\nVenue: Tagaytay.'));
assert(mail.searchParams.get('body').includes('Email: client@example.com'));
assert.equal(elements.get('copy-fallback').hidden,false);
assert(elements.get('prepared-inquiry').value.includes('To: mlagellon@gmail.com'));
assert(elements.get('inquiry-status').textContent.includes('has not been sent yet'));
console.log('PASS: inquiry addressed to mlagellon@gmail.com; subject/body safely encoded; sender email included; manual fallback available; no false delivery confirmation.');
